#!/bin/sh

# This file is run automatically when an X session starts
# via running "startx" or "xinit".

# Source script files from xinitrc.d directory
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set keyboard typematic delay and rate
xset r rate 250 30

# Apply custom keyboard layout
xkbcomp -I$HOME/.config/xkb ~/.config/xkb/keymap/mykbd "$DISPLAY"

# Read Xresources file
xres="${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources"
[ -f "$xres" ] && xrdb "$xres"
unset xres

# Export wacom related variables
. "$HOME/.scripts/wacom/wacom-setup"


# Start the window/display manager
exec spectrwm
