#!/bin/sh

# This file is executed whenever an X session is started,
# it should be executed by the window manager/desktop environment.

# Autostart utilities
xwallpaper --zoom ~/.config/wallpaper
flameshot &
dunst &
sxhkd &
xidlehook --not-when-audio --timer 600 'physlock' '' --timer 1200 'systemctl suspend' '' &

# Autostart other programs
[ -f ~/.config/autostart ] && . ~/.config/autostart
