#!/bin/sh

# Color definitions
LAYOUT_COL='%{F#FF9F00}'
STATE_COL='%{F#6B7}'
FLAGS_COL='%{F#97F}'

EVENTS=node_focus node_state node_flag node_remove desktop_layout desktop_focus
#shellcheck disable=SC2086
bspc subscribe $EVENTS | while read -r _; do
    out="$LAYOUT_COL"
    report="$(bspc wm -g)"

    unset flags
    IFS=:
    for i in L${report##*:L}; do
        case "$i" in
            LT) out="$out %{F-}%{T0}" ;;
            LM) out="$out %{F-}%{T0}" ;;
            L*) out="$out ?%{F-}%{T0}" ;;
            T*) state="${i#T}" ;;
            G*) flags="${i#G}" ;;
        esac
    done
    unset IFS

    windows="$(bspc query -N -d -n .window.!hidden)"
    focused="$(bspc query -N -n)"
    wcount="$(echo "$windows" | wc -w)"
    widx=1
    for wid in $windows; do
        [ "$wid" = "$focused" ] && break
        widx=$((widx + 1))
    done

    if [ "$wcount" -gt 0 ]; then
        out="$out $widx/$wcount"
    else
        out="$out -"
    fi

    printf "%s\n" "$out $STATE_COL$state$FLAGS_COL$flags"
done
