local modpath = (...)
require(modpath .. ".colorscheme")
require(modpath .. ".indent")
require(modpath .. ".marker")
require(modpath .. ".netrw")
require(modpath .. ".new_file_templates")
require(modpath .. ".quickfix_loc_lists")
require(modpath .. ".shada")
require(modpath .. ".term_insert_mode")
