#!/bin/sh

# Gracefully exit if bspc is not available
[ -z "$(command -v bspc)" ] && {
    echo 'bspwmrc: bspc required, but not detected' >&2
    exit
}

# Set up monitors
# the first monitor will contain a unique _sp desktop for hiding
# windows like scratchpads and minimized
desktops='1 2 3 4 5 6 7 8 9   '
onlyfirst='_sp'
num=0
for mon in $(bspc query -M --names); do
    bspc monitor "$mon" -n "$num" -d $desktops $onlyfirst
    onlyfirst=
    num=$((num + 1))
done

# Window rules - always use 'bspc rule...' when possible,
# to minimize the overhead of the external rules script.
bspc rule -a '*:sp'       state=floating
bspc rule -a '*:floatme'  state=floating
bspc rule -a 'firefox'       desktop=
bspc rule -a 'Brave-browser' desktop=
bspc rule -a 'Chromium'      desktop=
bspc rule -a 'Thunderbird' desktop=
bspc rule -a 'discord'     desktop=
bspc rule -a 'Carla2:carla' state=floating
bspc rule -a 'Sxiv:sxiv'    state=floating
bspc rule -a 'weka-gui-GUIChooser' state=floating
bspc rule -a 'flameshot:flameshot' state=floating border=off
bspc config external_rules_command ~/.scripts/bspwm/external_rules.sh

# Behavior Settings
bspc config split_ratio 0.5
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config directional_focus_tightness high
bspc config removal_adjustment false
bspc config pointer_motion_interval 17
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1
bspc config swallow_first_click false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config mapping_events_count 0
bspc config ignore_ewmh_focus false
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts false
bspc config honor_size_hints true
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors false

# Appearance Settings
bspc config normal_border_color '#666'
bspc config active_border_color '#FFA000'
bspc config focused_border_color '#A0FF00'
bspc config presel_feedback_color '#408800'
bspc config presel_feedback true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config center_pseudo_tiled true
bspc config window_gap 10
bspc config border_width 2

# Run polybar
~/.scripts/bspwm/bar_toggle.sh

# Run xprofile autostart script
# Using sxhkd as a condition to determine whether or not xprofile
# should be run is a dirty solution, but it works.
pidof -q sxhkd || {
    xprofile="$HOME/.config/X11/xprofile"
    [ -f "$xprofile" ] && . "$xprofile"
}

# Display normal cursor outside of windows
xsetroot -cursor_name left_ptr
