.de KB
.IP "\\(bu \\fB\\$1\\fP" 25
\\$2
.sp -1
..
.TH KEYBINDS 7 2024-01-14 keybinds
.SH DESCRIPTION
.P
This man page lists all global keybindings available on my linux machine.
.br
For more details about my setup, visit
.UR https://github.com/randoragon/dotfiles
my dotfiles repo
.UE .
.
.SH KEYBINDINGS
.
.SS MISCELLANEOUS
.KB "Super Shift /"         "Open keybinds help"
.KB "Super Ctrl r"          "Reload sxhkd config"
.KB "Super Shift r"         "Reload spectrwm config"
.KB "Super b"               "Toggle status bar"
.KB "Super Shift w"         "Randomize wallpaper"
.KB "Super Ctrl Shift w"    "Set wallpaper to black"
.
.sp
.SS LAUNCHERS
.P
.KB "Super Return"      "Terminal emulator"
.KB "Super o"           "bemenu_run"
.KB "Super g"           "mousemode"
.KB "Super c"           "snippet"
.KB "Ctrl Alt w"        "surf"
.KB "Ctrl Alt d"        "Discord"
.KB "Ctrl Alt b"        "Book menu"
.KB "Super Shift o"     "Copy password"
.KB "Super Ctrl o"      "Copy user"
.KB "Super Shift n"     "Open note"
.KB "Super Ctrl n"      "Edit note"
.KB "Printscrn"         "Flameshot (interactive)"
.KB "Ctrl Printscrn"    "Capture screen to clipboard"
.
.sp
.SS WINDOWS
.P
.KB "Super q"            "Close"
.KB "Super Ctrl q"       "Kill"
.KB "Super \e"           "Minimize"
.KB "Super Shift \e"     "Unminimize"
.KB "Super r"            "Raise"
.sp
.KB "Super j"          "Focus next"
.KB "Super k"          "Focus previous"
.KB "Super u"          "Swap with next"
.KB "Super i"          "Swap with previous"
.sp
.KB "Super Shift Space"     "Toggle floating"
.KB "Super f"               "Toggle maximized"
.KB "Super Shift f"         "Toggle fullscreen"
.sp
.sp
.SS WINDOWS (TILED)
.P
.KB "Super s"               "Swap with master"
.KB "Super a"               "Focus master"
.KB "Super Shift 0"         "Jump to arbitrary window"
.
.sp
.SS WINDOWS (FLOATING)
.P
.KB "Super Shift h"  "Move west"
.KB "Super Shift j"  "Move south"
.KB "Super Shift k"  "Move north"
.KB "Super Shift l"  "Move east"
.sp
.KB "Super Ctrl h"  "Shrink horizontal"
.KB "Super Ctrl j"  "Grow vertical"
.KB "Super Ctrl k"  "Shrink vertical"
.KB "Super Ctrl l"  "Grow horizontal"
.sp
.KB "Super Ctrl Shift h"  "Throw west"
.KB "Super Ctrl Shift j"  "Throw south"
.KB "Super Ctrl Shift k"  "Throw north"
.KB "Super Ctrl Shift l"  "Throw east"
.KB "Super Ctrl Shift n"  "Throw center"
.
.sp
.SS WORKSPACES
.P
.KB "Super ["               "Select previous (occupied)"
.KB "Super ]"               "Select next (occupied)"
.KB "Super Ctrl ["          "Select previous"
.KB "Super Ctrl ]"          "Select next"
.sp
.KB "Super 1..6"            "Select workspace 1..6"
.KB "Super Shift 1..6"      "Move to workspace 1..6"
.KB "Super W"               "Select Browser workspace"
.KB "Super Shift W"         "Move to Browser workspace"
.KB "Super E"               "Select E-Mail workspace"
.KB "Super Shift E"         "Move to E-Mail workspace"
.KB "Super D"               "Select Discord workspace"
.KB "Super Shift D"         "Move to Discord workspace"
.KB "Super Tab"             "Select last workspace"
.sp
.KB "Super Space"           "Toggle Scratch terminal"
.KB "Super M"               "Toggle Scratch music player"
.KB "Super N"               "Toggle Scratch RSS viewer"
.KB "Super /"               "Toggle Scratch calculator"
.sp
.KB "Super ,"               "Focus previous monitor"
.KB "Super ."               "Focus next monitor"
.KB "Super Shift ,"         "Move to previous monitor"
.KB "Super Shift ."         "Move to next monitor"
.
.sp
.SS TILING LAYOUTS
.KB "Super 9"               "Layout: vertical"
.KB "Super Shift 9"         "Layout: horizontal"
.KB "Super Shift 0"         "Layout: max"
.KB "Super Shift s"         "Flip layout"
.KB "Super Shift -"         "Decrement no. windows in the master area"
.KB "Super Shift ="         "Increment no. windows in the master area"
.KB "Super h"               "Shrink master area"
.KB "Super l"               "Grow master area"
.
.sp
.SS MUSIC / VOLUME
.KB "Super p"               "Play/pause"
.KB "Super Shift p"         "Stop"
.KB "Super ;"               "Previous"
.KB "Super '"               "Next"
.KB "Super Shift ;"         "Seek -5s"
.KB "Super Shift '"         "Seek +5s"
.KB "Super -"               "Volume -2%"
.KB "Super ="               "Volume +2%"
.KB "Super Backspace"       "Toggle mute"
.KB "Super Ctrl ="          "Add to playlist"
