.de KB
.IP "\\(bu \\fB\\$1\\fP" 25
\\$2
.sp -1
..
.TH KEYBINDS 7 2022-02-20 keybinds
.SH DESCRIPTION
.P
This man page lists all global keybindings available on my linux machine.
.br
For more details about my setup, visit
.UR https://github.com/randoragon/dotfiles
my dotfiles repo
.UE .
.
.SH KEYBINDINGS
.
.SS MISCELLANEOUS
.KB "Super Shift /"         "Open keybinds help"
.KB "Super Ctrl r"          "Reload sxhkd config"
.KB "Super Shift w"         "Randomize wallpaper"
.KB "Super Ctrl Shift w"    "Set wallpaper to black"
.
.SS LAUNCHERS
.P
.KB "Super Return"      "Terminal emulator"
.KB "Super o"           "dmenu_run"
.KB "Super g"           "mousemode"
.KB "Super c"           "snippet"
.KB "Ctrl Alt i"        "File explorer"
.KB "Ctrl Alt w"        "surf"
.KB "Ctrl Alt d"        "Discord"
.KB "Ctrl Alt f"        "fsearch"
.KB "Ctrl Alt b"        "Book menu"
.KB "Super Shift o"     "Copy password"
.KB "Super Ctrl o"      "Copy user"
.KB "Super Shift n"     "Open note"
.KB "Super Ctrl n"      "Edit note"
.KB "Printscrn"         "Flameshot (interactive)"
.KB "Ctrl Printscrn"    "Capture screen to clipboard"
.
.sp
.SS NODES (WINDOWS)
.P
.KB "Super q"            "Close"
.KB "Super Ctrl q"       "Kill"
.KB "Super Shift m"      "Minimize"
.KB "Super Ctrl m"       "Unminimize"
.sp
.KB "Super Left/h"          "Focus left"
.KB "Super Down/j"          "Focus down"
.KB "Super Up/k"            "Focus up"
.KB "Super Right/l"         "Focus right"
.sp
.KB "Super Shift Left/h"    "Move left"
.KB "Super Shift Down/j"    "Move down"
.KB "Super Shift Up/k"      "Move up"
.KB "Super Shift Right/l"   "Move right"
.sp
.KB "Super Ctrl Left/h"  "Shrink left"
.KB "Super Ctrl Down/j"  "Grow down"
.KB "Super Ctrl Up/k"    "Shrink up"
.KB "Super Ctrl Right/l" "Grow right"
.sp
.KB "Super u"               "Focus cycle next"
.KB "Super i"               "Focus cycle previous"
.KB "Super Shift u"         "Focus cycle floating next"
.KB "Super Shift i"         "Focus cycle floating previous"
.KB "Super Ctrl u"          "Focus cycle tiled next"
.KB "Super Ctrl i"          "Focus cycle tiled previous"
.sp
.KB "Super Ctrl Shift i"       "Select parent"
.KB "Super Ctrl Shift u"       "Select 1st child"
.KB "Super Ctrl Shift o"       "Select 2nd child"
.sp
.KB "Super y"                     "Send to presel"
.KB "Super Shift y"               "Send marked to presel"
.sp
.KB "Super t"               "Toggle tiled"
.KB "Super Ctrl t"          "Toggle pseudo-tiled"
.KB "Super Shift Space"     "Toggle floating"
.KB "Super f"               "Toggle fullscreen"
.sp
.KB "Super Ctrl a"       "Toggle marked"
.KB "Super Ctrl s"       "Toggle sticky"
.KB "Super Ctrl z"       "Toggle private"
.KB "Super Ctrl x"       "Toggle locked"
.sp
.KB "Super Ctrl Shift e" "Equalize all or selected"
.KB "Super Ctrl Shift b" "Balance all or selected"
.
.sp
.SS NODES (WINDOWS) \- TILED
.P
.KB "Super Ctrl Shift Left/h"  "Toggle west presel"
.KB "Super Ctrl Shift Down/j"  "Toggle south presel"
.KB "Super Ctrl Shift Up/k"    "Toggle north presel"
.KB "Super Ctrl Shift Right/l" "Toggle east presel"
.KB "Super Ctrl Shift 1..9"    "Set presel size to 90..10%"
.sp
.KB "Super s"               "Swap current with biggest/last"
.KB "Super Shift s"         "Swap with sibling"
.KB "Super Ctrl Shift s"    "Swap siblings of sibling"
.sp
.kB "Super z"               "Rotate counterclockwise"
.kB "Super x"               "Rotate clockwise"
.sp
.KB "Super 0"               "Jump to arbitrary window"
.KB "Super Shift 0"         "Bring arbitrary window"
.KB "Super Ctrl 0"          "Swap with arbitrary window"
.
.sp
.SS NODES (WINDOWS) \- FLOATING
.P
.KB "Super Ctrl Shift Left/h"  "Throw west"
.KB "Super Ctrl Shift Down/j"  "Throw south"
.KB "Super Ctrl Shift Up/k"    "Throw north"
.KB "Super Ctrl Shift Right/l" "Throw east"
.KB "Super Ctrl Shift n"       "Throw center"
.
.sp
.SS TAGS / WORKSPACES
.P
.KB "Super a"               "Toggle monocle layout"
.KB "Super Ctrl Shift 0"    "Toggle gaps"
.sp
.KB "Super ["               "Select previous (occupied)"
.KB "Super ]"               "Select next (occupied)"
.KB "Super Ctrl ["          "Select previous"
.KB "Super Ctrl ]"          "Select next"
.sp
.KB "Super 1..9"            "Select tag 1..9"
.KB "Super Shift 1..9"      "Move to tag 1..9"
.KB "Super W"               "Select Browser tag"
.KB "Super Shift W"         "Move to Browser tag"
.KB "Super E"               "Select E-Mail tag"
.KB "Super Shift E"         "Move to E-Mail tag"
.KB "Super D"               "Select Discord tag"
.KB "Super Shift D"         "Move to Discord tag"
.KB "Super Tab"             "Select last tag"
.KB "Super Shift Tab"       "Move to last tag"
.sp
.KB "Super Space"           "Toggle Scratch Terminal"
.KB "Super M"               "Toggle Scratch ncmpcpp"
.KB "Super N"               "Toggle Scratch DualBoat"
.sp
.KB "Super ,"               "Focus Previous Monitor"
.KB "Super ."               "Focus Next Monitor"
.KB "Super Shift ,"         "Move to Previous Monitor"
.KB "Super Shift ."         "Move to Next Monitor"
.
.sp
.SS STATUS BAR
.P
.KB "Super b"               "Toggle visibility"
.KB "Super Shift"           "Restart"
.KB "Super Ctrl b"          "Kill"
.
.sp
.SS MUSIC / VOLUME
.KB "Super p"               "Play/pause"
.KB "Super Shift p"         "Stop"
.KB "Super ;"               "Previous"
.KB "Super '"               "Next"
.KB "Super Shift ;"         "Seek -5s"
.KB "Super Shift '"         "Seek +5s"
.KB "Super -"               "Volume -2%"
.KB "Super ="               "Volume +2%"
.KB "Super Backspace"       "Toggle mute"
.KB "Super Ctrl ="          "Add to playlist"
