#!/usr/bin/sh

barh=19     # dwm bar height
pad=2       # padding from top and bottom

bath="$(( barh - (2*pad) ))" # battery height
batw=8                      # battery width
bd=1                         # battery border
bdcol="#BBBBBB"              # border color
bgcol="#303030"              # battery bg color
midw=4                       # small top rect width

output=
for path in /sys/class/power_supply/BAT?; do
    capacity="$(cat -- "$path/capacity")"
    [ -z "$capacity" ] && exit
    status="$(cat -- "$path/status")"

    output="^c$bdcol^"

    # Draw base battery
    output="$output^r0,$(( pad + bd )),$batw,$(( barh - (2*pad) - bd ))^"
    output="$output^r$(( (batw - midw) / 2 )),$pad,$midw,$(( barh - (2*pad) - bd ))^"
    if [ "$status" = "Charging" ]; then
        col="#00FFFF"
    else
        red="$(( 255 - (255 * capacity / 100) ))"
        green="$(( capacity * 255 / 100 ))"
        col="#$(printf "%02x" "$red")$(printf "%02x" "$green")"00
    fi
    output="$output^c$col^^r$bd,$(( pad + (2*bd) )),$(( batw - (2*bd) )),$(( bath - (3*bd) ))^"

    # Cover not filled parts with bgcol
    fillh="$(( (bath - (3*bd)) * (100 - capacity) / 100 ))"
    output="$output^c$bgcol^^r$bd,$(( pad + (2*bd) )),$(( batw - (2*bd) )),$fillh^"
    output="$output^c$bdcol^"

    echo "$output^f$(( batw + 2 ))^$capacity%"
    exit
done
