#!/bin/sh

# Save the number of pending pacman updates to a file.
# The file should be read systematically by dwmblocks.
# Background color is sea-green in case of kernel updates
# and yellow otherwise.
#
# Dependencies: pacman-contrib

UPDATES="$(checkupdates)"
FILE=~/.cache/dwmbupdates

if [ -n "$UPDATES" ]; then
    COUNT="$(printf "%s\n" "$UPDATES" | wc -l)"
    FG="FFFF00"
    BG="222200"
    printf "%s" "$UPDATES" | grep -q '^linux ' && { FG="00FFAA" BG="003311"; }
    OUTPUT="^b#$BG^^c#$FG^  $COUNT "
    echo "$OUTPUT" >"$FILE"
    echo "  $COUNT"
else
    :>"$FILE"
fi

pkill -RTMIN+4 -x dwmblocks
