#!/bin/sh
# Source: https://github.com/LukeSmithxyz/voidrice/blob/master/.config/sxiv/exec/key-handler
#
# KeyBindings (all precede with <C-x>):
# - w   : set as wallpaper
# - <   : rotate left (edit)
# - >   : rotate right (edit)
# - ?   : rotate 180 (edit)
# - |   : flip horizontally (edit)
# - _   : flip vertically (edit)
# - C-c : copy image to clipboard
# - y   : copy filename to clipboard
# - Y   : copy full path to clipboard

while read -r file; do
    case "$1" in
        'w') chwall "$file" ;;
        'greater') magick -rotate 90 "$file" "$file" ;;
        'less') magick -rotate -90 "$file" "$file" ;;
        'question') magick -rotate 180 "$file" "$file" ;;
        'bar') magick -flop "$file" "$file" ;;
        'underscore') magick -flip "$file" "$file" ;;
        'C-c') wl-copy <"$file" &&
                 notify-send -i "$(readlink -f "$file")" "$file" "Image copied to clipboard" ;;
        'y') printf "%s" "$(basename -- "$file")" | wl-copy &&
                 notify-send -i "$(readlink -f "$file")" "$(basename -- "$file")" "Name copied to clipboard" ;;
        'Y') readlink -f "$file" | tr -d '\n' | wl-copy &&
                 notify-send -i "$(readlink -f "$file")" "$(readlink -f "$file")" "Path copied to clipboard" ;;
        'g') notify-send -i "$(readlink -f "$file")" "$file" "Launching in GIMP..." && gimp "$file" & ;;
        'd') [ "$(printf "yes\nno\n" | bemenu -p "Delete image?")" = yes ] && rm -f -- "$file" ;;
    esac
done
