#!/bin/sh

# Color definitions
STATE_COL='%{F#6B7}'
FLAGS_COL='%{F#97F}'

EVENTS=node_focus node_state node_flag node_remove desktop_layout desktop_focus
#shellcheck disable=SC2086
bspc subscribe $EVENTS | while read -r _; do
    mon="$(bspc query -M -m --names)"
    report="L$(bspc wm -g | perl -pe "s/.*[Mm]$mon:.*?:L//")"

    IFS=:
    unset state flags
    for i in ${report%%:[Mm]*}; do
        case "$i" in
            T*) state="${i#T}"; [ -n "$flags" ] && break ;;
            G*) flags="${i#G}"; [ -n "$state" ] && break ;;
        esac
    done
    unset IFS

    printf "%s\n" "$STATE_COL$state$FLAGS_COL$flags"
done
