---

bar:
  location: top
  height: 20
  background: 333333ff

  left:
    - river:
        anchors:
          on-click: &onclick
            left: "sh -c 'riverctl set-focused-tags $((1 << ({id} - 1)))'"
            right: "sh -c 'riverctl toggle-focused-tags $((1 << ({id} - 1)))'"
          focus-string: &focusstring
            deco:
              background:
                color: 666666ff
            margin: 5
            text: "{id}"
            on-click: *onclick
          urgent-string: &urgentstring
            deco:
              background:
                color: ff4444ff
            margin: 5
            text: "{id}"
            on-click: *onclick
        content:
          map:
            default:
              map:
                default:
                  string:
                    margin: 5
                    text: "{id}"
                    on-click: *onclick
                conditions:
                  id == 10:
                    string:
                      margin: 5
                      text: "w"
                      on-click: *onclick
                  id == 11:
                    string:
                      margin: 5
                      text: "e"
                      on-click: *onclick
                  id == 12:
                    string:
                      margin: 5
                      text: "d"
                      on-click: *onclick
                  id == 13:
                    string:
                      margin: 5
                      text: "n"
                      on-click: *onclick
                  id == 14:
                    string:
                      margin: 5
                      text: "m"
                      on-click: *onclick
            conditions:
              ~occupied && ~focused:
                empty: {}
              urgent:
                map:
                  default:
                    string:
                      <<: *urgentstring
                      text: "{id}"
                  conditions:
                    id == 10:
                      string:
                        <<: *urgentstring
                        text: "w"
                    id == 11:
                      string:
                        <<: *urgentstring
                        text: "e"
                    id == 12:
                      string:
                        <<: *urgentstring
                        text: "d"
                    id == 13:
                      string:
                        <<: *urgentstring
                        text: "n"
                    id == 14:
                      string:
                        <<: *urgentstring
                        text: "m"
              focused:
                map:
                  default:
                    string:
                      <<: *focusstring
                      text: "{id}"
                  conditions:
                    id == 10:
                      string:
                        <<: *focusstring
                        text: "w"
                    id == 11:
                      string:
                        <<: *focusstring
                        text: "e"
                    id == 12:
                      string:
                        <<: *focusstring
                        text: "d"
                    id == 13:
                      string:
                        <<: *focusstring
                        text: "n"
                    id == 14:
                      string:
                        <<: *focusstring
                        text: "m"

  center:
    - river:
        title:
          string:
            text: "{title}"
        content:
          empty: {}

  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  conditions:
                    muted:
                      string:
                        margin: 5
                        text: "X {cubic_volume}"
                    ~muted:
                      string:
                        margin: 5
                        text: "> {cubic_volume}"
                  on-click:
                    left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                    right: "qpwgraph"

    - label: &sep
        content:
          string:
            text: "|"

    - script:
        path: ~/.scripts/yambar/storage
        poll-interval: 10000
        content:
          string:
            margin: 5
            text: "{str}"

    - label: *sep

    - script:
        path: ~/.scripts/yambar/gpg_expire
        poll-interval: 3600000
        content:
          string:
            margin: 5
            text: "{str}"

    - label: *sep

    - clock:
        date-format: "%a %m/%d"
        time-format: "%H:%M:%S"
        content:
          string:
            margin: 5
            text: "{date}  {time}"
            on-click:
              left: "foot -a floatme sh -c 'cal -3 --color=always | less -R'"

    - battery:
        name: "BAT0"
        content:
          map:
            default:
              string:
                  margin: 5
                  text: "*{capacity}%"
            conditions:
              state == "discharging":
                string:
                    margin: 5
                    text: "v{capacity}%"
              state == "charging":
                string:
                    margin: 5
                    text: "^{capacity}%"
              state == "unknown":
                empty: {}
