#!/bin/sh

# This is the configuration script of the River Wayland compositor.
#
# To keep this file from growing too big, I split a lot of repetitive
# code into separate scripts which are sourced by this main one.
#
# This script should only contain core settings, such as keyboard and
# mouse behavior, appearance, external layout program and keybindings
# for basic things like tag/view manipulation and session management.
#
# All other configuration should be logically divided into standalone
# executable shell scripts and put inside the init.d directory.

# Change directory to the one containing this script
cd "$(dirname -- "$0")" || exit 1

# Keyboard configuration
riverctl set-repeat 30 250
riverctl default-attach-mode below
riverctl keyboard-layout-file "${XDG_CONFIG_HOME:-$HOME/.config}/xkb/keymap/mykbd"

# Mouse settings
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl focus-follows-cursor normal

# Appearance
riverctl background-color 0x111111
riverctl border-color-focused 0xeeeeee
riverctl border-color-unfocused 0x222222
riverctl border-color-urgent 0xee2222
riverctl border-width 1

# Basic keybindings
riverctl map normal Super Return spawn "$TERMINAL"
riverctl map normal Super O spawn 'bemenu-run -i -c -W0.8 -l20 -B5 -R10'
riverctl map normal Super+Shift Q spawn 'quitmenu'

# Tag keybindings
tagmap () {
    riverctl map         normal Super               "$1" set-focused-tags     "$2"
    riverctl map -repeat normal Super+Control       "$1" toggle-focused-tags  "$2"
    riverctl map -repeat normal Super+Shift         "$1" set-view-tags        "$2"
    riverctl map -repeat normal Super+Control+Shift "$1" toggle-view-tags     "$2"
}
i=0
for key in $(seq 1 9) W E D N M; do
    tagmap "$key" $(( 1 << i ))
    i=$((i + 1))
done
riverctl map -repeat normal Super Tab focus-previous-tags
riverctl map -repeat normal Super+Shift Tab send-to-previous-tags

# View keybindings
riverctl map normal Super Q close
riverctl map -repeat normal Super J focus-view next
riverctl map -repeat normal Super K focus-view previous
riverctl map -repeat normal Super U swap next
riverctl map -repeat normal Super I swap previous
riverctl map -repeat normal Super S zoom
riverctl map normal Super+Shift Space toggle-float
riverctl map normal Super F toggle-fullscreen

# Floating views
riverctl map normal Super+Control+Shift H snap left
riverctl map normal Super+Control+Shift J snap down
riverctl map normal Super+Control+Shift K snap up
riverctl map normal Super+Control+Shift L snap right
riverctl map -repeat normal Super+Shift H move left  50
riverctl map -repeat normal Super+Shift J move down  50
riverctl map -repeat normal Super+Shift K move up    50
riverctl map -repeat normal Super+Shift L move right 50
riverctl map -repeat normal Super+Control H resize horizontal -50
riverctl map -repeat normal Super+Control J resize vertical    50
riverctl map -repeat normal Super+Control K resize vertical   -50
riverctl map -repeat normal Super+Control L resize horizontal  50

# Lock idle session
swayidle -w \
    timeout 600 waylock \
    before-sleep waylock &

# Source script files from init.d directory
if [ -d init.d ]; then
    for f in init.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Autostart other programs
[ -f ~/.config/autostart ] && . ~/.config/autostart
