# RANDORAGON's BEETS CONFIG

# Directory for beets to store raw data in
library: ~/.config/beets/library.db

# Directory to move amended items into
directory: ~/Music

# Formats used when producing output with beets list
format_item: $artist - $title
format_album: $albumartist - $album
sort_item: artist+ album+ disc+ track+
sort_album: albumartist+ album+
sort_case_insensitive: yes

# Import options
import: 
    write: no
    move: yes
    copy: no
    resume: ask
    incremental: no
    incremental_skip_later: no
    quiet: no
    detail: yes
    from_scratch: no
    log: ~/.config/beets/import.log
    languages: en pl de ja jp
    autotag: yes

# Paths
paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: $artist/no album/$title
    comp: Compilations/$album%aunique{}/$title

# PLUGINS ----------------------------------------------------
# https://beets.readthedocs.io/en/stable/plugins/index.html
# fetchart       : download album art
# lastgenre      : download genre
# chroma         : enables matching by acoustic fingerprint instead of just tags
# fromfilename   : guesses metadata from filename
# acousticbrainz : fetch tags from AcousticBrainz
# edit           : edit tags with any text editor
# embedart       : embed album art directly into the music files
# ftintitle      : converts tags like "artist feat. guest - title" to "artist - title feat. guest"
# mbsync         : update MusicBrainz tags with "beet mbsync QUERY". Affects only items with MusicBrainzID
# mpdstats       : collects play count, skip count, last played and rating from MPD
# mpdupdate      : updates MPD library everytime beets library changes
# replaygain     : calculates replaygain
# thumbnails     : adds metadata for displaying file thumbnails in thunar etc.
# fuzzy          : enables fuzzy searching by prefixing the query with ~
# info           : enables listing quaried items' tag information
# spotify        : allows to create spotify playlists from local library
# duplicates     : finds duplicate tracks or albums
plugins: fetchart lastgenre chroma acousticbrainz edit embedart ftintitle mbsync mpdstats mpdupdate replaygain thumbnails fuzzy info spotify duplicates fromfilename

chroma:
    auto: yes

acoustid:
    # Send local fingerprints to with "beet submit"
    apikey: plCTgUVJgu

acousticbrainz:
    auto: yes
    force: no
    tags: [] # all

edit:
    itemfields: track title artist album
    albumfields: album albumartist

fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 500
    enforce_ratio: no
    sources: filesystem covertart itunes amazon albumart wikipedia google
    google_key: GOOGLE_KEY_GOES_HERE
    store_source: no

embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 500
    remove_art_file: yes

ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

lastgenre:
    auto: yes
    canonical: no
    count: 2
    fallback: ''
    force: no
    min_weight: 10
    prefer_specific: no
    source: track
    separator: ' '
    whitelist: yes

mpd:
    port: 6601
    rating: yes
    rating_mix: 0.75

replaygain:
    backend: gstreamer
    auto: yes
    overwrite: no
    targetlevel: 89

thumbnails:
    auto: yes
    force: no
    dolphin: no

fuzzy:
    threshold: 0.7
    prefix: "~"

web:
    host: 127.0.0.1
    port: 8337
    reverse_proxy: false
    include_paths: false

duplicates:
    keys: [mb_trackid, mb_albumid]
    album: no
    count: no
    delete: no
    full: no
    merge: no
    path: yes

# ENDOF PLUGINS ----------------------------------------------
