#!/bin/sh

# This file is for storing abbreviations for commands

# General
alias ls='ls --color=auto'
alias setkblayoutpl='setxkbmap -layout pl'
alias setlangus='LANG=en_US.UTF-8 && LC_ALL="en_US.UTF-8"'
alias rm='rmtrash'
alias rmdir='rmdirtrash'
alias nnn='nnn -R'
alias sxiv='sxiv -qab'
alias fzf='fzf --bind=ctrl-d:half-page-down,ctrl-u:half-page-up'
alias xo='xdg-open'

# Git 
alias gs="git status"
alias ga="git add"
alias gd="git diff"
alias gds="git diff --staged"
alias gc="git commit"
alias gp="git push"
alias grs="git restore --staged"

# Update everything
alias sysupdate='sudo pacman -Syu && yay -Syu && sudo snap refresh && sudo youtube-dl -U && updatecount'
if [ "$HOSTNAME" = "gallium" ]; then
    export TERM=xterm-termite
    alias sysupdate='sudo apt update && sudo apt upgrade && sudo snap refresh'
    # enable apt auto-completion (https://askubuntu.com/questions/133086/bash-tab-auto-complete-not-working-for-apt)
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        . /etc/bash_completion
    fi
fi
