#!/bin/sh

# This script's sole purpose is to output polybar-formatted text
# parsed from `newsboat -x print-unread`.

num="$(newsboat -x print-unread)"
num="${num%% *}"

bg="002222"
fg="00ffff"

if [ "$num" = 0 ]; then
    printf "\n"
else
    printf "%%{B#%s}%%{F#%s}   %s %%{F- B-}\n" "$bg" "$fg" "$num"
fi
