#!/bin/sh

# GENerate Stream MUsic List

# This script generates a markdown file of all music stored inside
# the Fair Use playlist.
#
# This script was created so that listing music for various streaming
# platforms is made easier.
#
# DEPENDENCIES:
# - id3ted

pl="$HOME/Music/Playlists/#Fair Use.m3u"
base="$HOME/Music"

export OUTFILE="playlist.md"

# Wipe the outfile
printf '' >"$OUTFILE"

while read -r relative; do
    f="$base/$relative"
    [ ! -f "$f" ] && {
        echo "gensmul: Invalid path detected, run plfix" >&2
        exit 1
    }

    # Extract relevant information
    tags="$(id3ted -l "$f")"
    artist="$(echo "$tags" | sed -n "s/^TPE1: //p")"
    title="$(echo "$tags" | sed -n "s/^TIT2: //p")"
    url="$(echo "$tags" | sed -n "s/^WXXX: \[origin\]: //p")"

    # Exit if any information is missing
    if [ -z "$artist" ] || [ -z "$title" ] || [ -z "$url" ]; then
        echo "gensmul: tags missing from file '$f'. Aborting."
        exit 1
    fi

    # Keep the outfile sorted while adding more lines
    # (method source: https://stackoverflow.com/a/10658677/10792539)
    echo "[$artist - $title]($url)" | sort -o "$OUTFILE" -m - "$OUTFILE"
done <"$pl"

# Add markdown list numbering
tmpfile="/tmp/$(basename "$0")_awk"
awk 'BEGIN{i=1} /.*/{printf "%d. % s\n",i,$0; i++}' "$OUTFILE" > "$tmpfile"
mv -- "$tmpfile" "$OUTFILE"
