#!/usr/bin/sh

case "$1" in 
    *.tar|*.tar.gz|*.tar.bz|*.tar.xz) tar tf "$1" ;;
    *.zip) unzip -l "$1" ;;
    *.rar) unrar l "$1" ;;
    *.7z) 7z l "$1" ;;
    *.jar) jar tf "$1" ;;
    *.pdf) pdftotext "$1" - ;;
    *) highlight -O ansi "$1" || cat "$1" ;;
esac
