#!/bin/sh

# Directories
mroot="$HOME/Music"
pldir="$mroot/Playlists"

playlists="$(find "$pldir" -maxdepth 1 -type f -name '*.m3u' \
    \! -path "$pldir/.Filtered.m3u" \
    \! -path "$pldir/.Rare.m3u" \
    \! -path "$pldir/.Generated.m3u" \
    \! -path "$pldir/hist.*.m3u" \
    \! -path "$pldir/#Rate[1-5].m3u" \
    -writable \
    -print0 | xargs -0l basename -- | sed 's/\.m3u$//')"
[ -z "$playlists" ] && notify-send -u low "pladd_select" "No playlists detected" && exit
playing="$(mpc current -f %file%)"
echo "$playing" | grep -q '^Download/\|^/' && notify-send -u low "pladd_select" "The current file is in the <u>Download</u> directory" && exit
chosen="$(printf '%s\n' "$playlists" | bemenu -i -p "Add to playlist:")"
[ -z "$chosen" ] && exit
printf "%s\n" "$chosen" | while read -r pl; do
    if [ "$pl" = "Fair Use" ]; then
        path="$mroot/$playing"
        printf "%s\n" "$path"
        alacritty --class Alacritty,floatme -e addfairuse "$path"
    else
        pladd "$pl"
    fi
done
