#!/bin/sh

# This script is used by an RSS reader to open live streams.
# Based on the URL it can distinguish between YouTube and Twitch
# livestreams and run an appropriate script to open it with live chat.

icon='/usr/share/icons/Adwaita/96x96/mimetypes/video-x-generic-symbolic.symbolic.png'

if printf "%s" "$@" | grep -qi 'youtube\.com'; then
    channel_id="$(printf "%s" "$@" | grep -o 'watch?v=.*')"
    channel_id="${channel_id##*=}"
    dunstify -u low -i "$icon" "$0" "starting <u>$channel_id</u> on YouTube..."
    printf "channel id: %s\n" "$channel_id"
    ytlive "$channel_id"
elif printf "%s" "$@" | grep -qi 'twitch\.tv'; then
    username="$(printf "%s" "$@" | grep -o 'tv\/.*')"
    username="${username##*/}"
    dunstify -u low -i "$icon" "$0" "starting <u>$channel_id</u> on Twitch..."
    twitch "$username"
else
    dunstify -u low -i "$icon" "$0" "streaming service not recognized"
    exit 1
fi
