#!/bin/sh

rootfs=$((1024 * $(df --output=avail / | tail -n1)))
homefs=$((1024 * $(df --output=avail /home | tail -n1)))

printf 'str|string|/ %s' \
    "$(numfmt --to iec --format %.1f "$rootfs")"

[ $homefs -ne $rootfs ] && {
    printf '  ~ %s' \
        "$(numfmt --to iec --format %.1f "$homefs")"
}

printf '\n\n'
